_schema: _schema
paths:
  uploads: static/uploads
  static: static
collections_config:
  pages:
    path: content
    name: Pages
    icon: wysiwyg
    disable_url: false
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
    url: [full_slug]
    _enabled_editors:
      - visual
    glob:
      - '!components.md'
  projects:
    path: content/projects
    glob:
      - '!_index.md'
    name: Projects
    icon: add_business
    disable_url: true
    description: ''
    preview:
      text:
      subtext:
      icon:
      icon_color:
      image:
        - key: thumbnail_image
      metadata:
      gallery:
    _enabled_editors:
    disable_add: false
    disable_add_folder: false
    disable_file_actions: false
_inputs:
  short_text:
    type: textarea
    cascade: true
  technologies:
    type: array
    options:
      empty_type:
      preview:
      structures:
        style: select
        id_key:
        values:
    cascade: true
_snippets_imports:
  hugo:
    exclude:
      - hugo_instagram
timezone: Pacific/Auckland
markdown:
  engine: commonmark
  options:
    xhtml: false
    breaks: false
    linkify: false
    typographer: false
    spaced_lists: false
    sentence_per_line: false
    gfm: true
    code_block_fences: '```'
    escape_snippets_in_code_blocks: false
    treat_indentation_as_code: true
    table: false
    strikethrough: false
    subscript: false
    superscript: false
    heading_ids: false
    attributes: false
