# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: "Two Col"
  description: Two columns of content with a heading
  icon: view_column
  tags: []

# Defines the structure of this component, as well as the default values
blueprint:
  heading: 
  column_one:
  column_two:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  column_one:
    type: markdown
  column_two:
    type: markdown